### PR TITLE
Whatever this is test

### PR DESCRIPTION
**Pull request by AndreyYevtukhov**
closes https://spryker.atlassian.net/browse/HRZ-2449

### CODE REVIEW

**Review by supproduction — CHANGES_REQUESTED** [review]
Reject

**Review by tolerants — CHANGES_REQUESTED** [review]
Reject!

**Review by tolerants — CHANGES_REQUESTED** [review]
Rejecto!

**Review by tolerants — CHANGES_REQUESTED** [review]
Rejecting again!

**Review by tolerants — CHANGES_REQUESTED** [review]
Redject!

**Review by tolerants — CHANGES_REQUESTED** [review]
R!

**Review by tolerants — DISMISSED** [review]
LGTM!

**Pull request closed without merging**
